version: '3'

services:
  db:
    restart: always
    container_name: postgres
    image: postgres:9.5.13-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=device_data
  node:
    restart: always
    build: ./node
    command: flask run --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 1
  app:
    restart: always
    build: ./app
    command: flask run --host 0.0.0.0 --port 5000
    environment:
      NODE_HOST: http://node:5000
      FLASK_DEBUG: 1
    depends_on:
      - node
    ports:
      - "80:5000"
  django:
    restart: always
    build: ./dj_app
    depends_on:
      - db
    ports:
      - "8080:8000"
    environment:
      - DB_URI=postgres://root:qwerty123@db:5432/device_data
